export const INGREDIENT_ADD = 'INGREDIENT_ADD';
export const INGREDIENT_REMOVE = 'INGREDIENT_REMOVE';
export const INGREDIENT_SET = 'INGREDIENT_SET';
export const INGREDIENT_FETCH_FAILED = 'INGREDIENT_FETCH_FAILED';
export const PURCHASING_ON = 'PURCHASING_ON';
export const PURCHASING_OFF = 'PURCHASING_OFF';