export const INGREDIENT_ADD = 'INGREDIENT_ADD';
export const INGREDIENT_REMOVE = 'INGREDIENT_REMOVE';
export const INGREDIENT_SET = 'INGREDIENT_SET';
export const INGREDIENT_FETCH_FAILED = 'INGREDIENT_FETCH_FAILED';

export const PURCHASING_ON = 'PURCHASING_ON';
export const PURCHASING_OFF = 'PURCHASING_OFF';

export const PURCHASE_INIT_START = 'PURCHASE_INIT_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
