export const INGREDIENT_ADD = 'INGREDIENT_ADD';
export const INGREDIENT_REMOVE = 'INGREDIENT_REMOVE';
export const INGREDIENT_SET = 'INGREDIENT_SET';
export const INGREDIENT_FETCH_FAILED = 'INGREDIENT_FETCH_FAILED';

export const PURCHASING_ON = 'PURCHASING_ON';
export const PURCHASING_OFF = 'PURCHASING_OFF';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';

export const ORDERS_FETCH_INIT = 'ORDERS_FETCH_INIT';
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS';
export const ORDERS_FETCH_FAIL = 'ORDERS_FETCH_FAIL';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';